### ISSUE TITLE
How to install in HomeAssistant

### ISSUE THREAD

**Issue by wasteduk** [MarvAmBass/docker-firetv-server#1]
Hi this is the solution I am looking for !
I have installed the standard firetv-server as documented https://www.home-assistant.io/components/media_player.firetv/ in a docker container.
The problem I am having in following you instructions are:

1. Do I need to install your docker-firetv-server instead? If so how to do this?
2. Should I connect to the firetv from within the container to generate the keys in /root/.android?
2.1 I had done so on my mac and run `adb connect <ip address> ` and copied the generated keys over to the docker server, but these did not work.
2.2 Trying to run `adb connect <ip address>` from within the docker container does not work as adb is not found.

Sorry for the very basic questions. I'll post back to the homeassistant forum a solution if I can get this working.

**Comment by MarvAmBass** [comment]
if you've installed it already without docker this container won't help you. Why do you want to use this container? is you solution not working?

1. -> take a look at how you work with docker containers etc.

2. -> doesn't matter where there where generated as long as the right keys are in this folder
2.1 -> don't know whats the problem with your keys, maybe wrong location or wrong permissions etc.
2.2 -> just install adb - but it's not required

**Comment by wasteduk** [comment]
The problem I am having with the standard firetv-server is:
```
File "/usr/local/lib/python2.7/site-packages/adb/adb_protocol.py", line 288, in Connect
    'Device authentication required, no keys available.')
adb.usb_exceptions.DeviceAuthError: Device authentication required, no keys available.
```
So I thought that your solution addresses this issue, but cannot work out how to install it. I typically use `docker pull` command to get a package but have not used that against github before. Will research more.
