### ISSUE TITLE
How do you add a firetv config yaml file reference to docker compose

### ISSUE THREAD

**Issue by BuxtonCalvin** [MarvAmBass/docker-firetv-server#3]
I've tried a number of ways to include the -c /some/path/to/firetv/config.yaml    but nothing works.  Do you know how to set this variable?? The -d flag using the environment variable works fine, but I have two firesticks that I would like to control, so I need to use the -c command switch.

**Comment by MarvAmBass** [comment]
I guess you're not mounting the configuration into the container am I right.

read about docker and volumes - or create your own container based on mine `FROM marvambass/firetv-server`

**Comment by MarvAmBass** [comment]
for two firetvs, start two containers
